# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 15:43
from __future__ import unicode_literals

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import django.contrib.postgres.fields.hstore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('domain', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
