# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 16:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20151227_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
