# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
