# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160103_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='utm_term',
            new_name='utm_content',
        ),
    ]
